version: "3.8"

services:
  node:
    container_name: SoloNode
    build:
      context: ./
      dockerfile: ./node.Dockerfile
    volumes:
      - ./:/home/Proyecto/Backend
    ports:
      - 8080:8080
    depends_on:
      - pischar

    environment:
      - URL=mongodb://pischar:27017/pischar

    links:
      - pischar

  pischar:
    container_name: pischar
    image: mongo
